name: Rust Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose 2>&1 | tee test_output.txt

    - name: Save test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_output.txt